env:
  global:
    - REACT_APP_COGNITO_USER_POOL_ID=us-east-1_fakepool
    - REACT_APP_COGNITO_CLIENT_ID=fakeclientid
language: node_js
node_js:
  - node
  - lts/*
os:
  - osx
  - linux
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test --bail --ci --coverage